# Generated by Django 6.0 on 2025-12-26 15:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culto',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de início do culto.'),
        ),
        migrations.RemoveField(
            model_name='culto',
            name='data',
        ),
        migrations.AlterModelOptions(
            name='culto',
            options={'ordering': ['data_hora'], 'verbose_name': 'Culto', 'verbose_name_plural': 'Cultos'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['nome'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='natculto',
            options={'ordering': ['nome'], 'verbose_name': 'Natureza do Culto', 'verbose_name_plural': 'Naturezas de Culto'},
        ),
        migrations.AlterModelOptions(
            name='obreiro',
            options={'ordering': ['nome'], 'verbose_name': 'Obreiro', 'verbose_name_plural': 'Obreiros'},
        ),
        migrations.AlterUniqueTogether(
            name='culto',
            unique_together={('local', 'data_hora')},
        ),
        migrations.AlterField(
            model_name='culto',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultos', to='escala.local'),
        ),
        migrations.AlterField(
            model_name='culto',
            name='nat_culto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultos', to='escala.natculto'),
        ),
        migrations.AlterField(
            model_name='local',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o local está ativo para novos cultos.'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(help_text='Nome do local do culto (ex: Sede, Congregação A).', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='natculto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se esta natureza de culto está ativa.'),
        ),
        migrations.AlterField(
            model_name='natculto',
            name='nome',
            field=models.CharField(help_text='Nome ou descrição da natureza do culto.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='obreiro',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o obreiro está ativo e pode ser escalado.'),
        ),
        migrations.AlterField(
            model_name='obreiro',
            name='cargo',
            field=models.CharField(help_text='Cargo ou função principal do obreiro na igreja.', max_length=50),
        ),
        migrations.AlterField(
            model_name='obreiro',
            name='nome',
            field=models.CharField(help_text='Nome completo do obreiro.', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mês da escala (1 a 12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.IntegerField(help_text='Ano da escala (ex: 2024).')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Publicada', 'Publicada')], default='Rascunho', help_text='Estado atual da escala (ex: Rascunho, Publicada).', max_length=20)),
            ],
            options={
                'verbose_name': 'Escala Mensal',
                'verbose_name_plural': 'Escalas Mensais',
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(help_text='Data de início da indisponibilidade.')),
                ('data_fim', models.DateTimeField(help_text='Data de Fim de indisponibilidade.')),
                ('motivo', models.CharField(help_text='Motivo da indisponibilidade.', max_length=255)),
                ('obreiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to='escala.obreiro')),
            ],
            options={
                'verbose_name': 'Indisponibilidade',
                'verbose_name_plural': 'Indisponibilidades',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EscalaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_escala', to='escala.culto')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='escala.escala')),
                ('obreiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='escala.obreiro')),
            ],
            options={
                'verbose_name': 'Item da Escala',
                'verbose_name_plural': 'Itens da Escala',
                'unique_together': {('culto', 'obreiro')},
            },
        ),
    ]
